files:
  - source: /content/en/*.*
    translation: /content/%two_letters_code%/%original_file_name%
  - source: /content/en/**/*.md
    ignore:
      - /content/en/archives/pic/*
      - /content/en/archives/3-5.93e/*
      - /content/en/archives/4.1.0/*
      - /content/en/archives/4.1.1/*
      - /content/en/archives/4.1.2/*
      - /content/en/archives/4.2.0/*
      - /content/en/archives/4.2.2-series/*
      - /content/en/archives/4.2.4-series/*
      - /content/en/archives/4.2.6-series/*
      - /content/en/support/servers/*
    translation: /content/%two_letters_code%/%original_path%/%original_file_name%
