files:
  - source: /content/en/*.*
    translation: /content/%two_letters_code%/%original_file_name%
  - source: /content/en/**/*.md
    ignore:
      - /content/en/archives/pic/*
    translation: /content/%two_letters_code%/%original_path%/%original_file_name%
